export const FETCH_SUBREDDIT = 'FETCH_SUBREDDIT';
export const FETCH_SUBREDDIT_SUCCESS = 'FETCH_SUBREDDIT_SUCCESS';
export const FETCH_SUBREDDIT_ERROR = 'FETCH_SUBREDDIT_ERROR';

export const REMOVE_ITEM = 'REMOVE_ITEM';
